- name: Delete project
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Get variables
    shell: export
    register: output
    
  - debug:
      msg: "{{ output }}"
    
  - name: Create Tower Ping job template
    ansible.tower.tower_job_template:
      name: "Ping"
      job_type: "run"
      organization: "Default"
      inventory: "Demo Inventory"
      project: "Demo Project"
      playbook: "hello_world.yml"
      state: "present"
      validate_certs: no
